# Generated by Django 5.2.4 on 2025-08-09 18:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note_title', models.CharField(max_length=255)),
                ('note_description', models.CharField(max_length=400)),
                ('user_notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.login_model')),
            ],
        ),
        migrations.CreateModel(
            name='motivation_agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot_info', models.CharField(max_length=255)),
                ('general_notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.new_notes')),
            ],
        ),
        migrations.CreateModel(
            name='Hopeful_agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hop_info', models.CharField(max_length=255)),
                ('general_notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.new_notes')),
            ],
        ),
        migrations.CreateModel(
            name='Happy_agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hap_info', models.CharField(max_length=255)),
                ('general_notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.new_notes')),
            ],
        ),
        migrations.CreateModel(
            name='general_agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_info', models.CharField(max_length=255)),
                ('general_notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.new_notes')),
            ],
        ),
        migrations.CreateModel(
            name='Funny_agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fun_info', models.CharField(max_length=255)),
                ('general_notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.new_notes')),
            ],
        ),
        migrations.CreateModel(
            name='Dramatic_agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dram_info', models.CharField(max_length=255)),
                ('general_notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.new_notes')),
            ],
        ),
        migrations.CreateModel(
            name='calm_agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calm_info', models.CharField(max_length=255)),
                ('general_notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.new_notes')),
            ],
        ),
        migrations.CreateModel(
            name='Reflective_agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_info', models.CharField(max_length=255)),
                ('general_notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.new_notes')),
            ],
        ),
    ]
